language: node_js
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: test
    install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
    script:
    - npm run lint
    - npm test
    - npm run coverage
  - stage: Build docker image and upload to AWS
    sudo: true
    services:
    - docker
    install: true
    if: tag IS present
    script:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region eu-west-1)
    - echo "Building docker image"
    - docker build -t wt-notification-api:$TRAVIS_BRANCH .
    - docker tag wt-notification-api:$TRAVIS_BRANCH 029479441096.dkr.ecr.eu-west-1.amazonaws.com/wt-notification-api:$TRAVIS_BRANCH
    - docker push 029479441096.dkr.ecr.eu-west-1.amazonaws.com/wt-notification-api:$TRAVIS_BRANCH
  - stage: Start service from docker with latest merged tag
    install: true
    sudo: true
    if: branch = release/playground
    script:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - npm run deploy-aws-playground
env:
  global:
  - secure: tLvEO5D9LG936jFvyd9kE46EA7qiprUJzdAo80fQ9qn6TYbHGk1sRpmQXS7REm0WLfduz8al/fFbU2kJ93SP/U5jzKmodC8GzYcU74S4cX0FZO9ghAopp6zvKxKe+OHHw7zrqAogCuHwxXQMMQjW83BvTQ2XfrfjljHVBIc9uzhp6JkdubOzDYEdbnnz+I1iLuEP4chsPnj/iUIjISJ2UoqacBVpW3ek/wLa5EGyj2J1Y+AfW/ioKy6k+FcXniRey57e3wp0kwRZYLSqJRNF8cjNGHfAsKgEgnRwDK8fXcM3D9yqopQATjJZaw6AGxSM67TecAFr/zchhBKOVOPKpvU/ke8tFW2hGGK7RzVEkM2y7vepeH3FPemj8LfVlphuVlOSx53Ig48DyNSCbzoLzPP8yeUssklx8JNDlhKfzJdesGP+elkyW8rNjc/LWPu2QSV3z930eMuPNGsykE/0rBztM4uulQrOuKrAfZ7mBX58YW4eTG3HR9z0DQL9WrcjW8/juK1LAx8f3fyGSL9tsAD0E7LkBtdJvG3Mp5hg/AnpeZthIi6lKgIIrVfS4rH+/IXGJnh7FR0IUD5DyOC3rjBTVIj2/MT43zTWKmKT8aGqLNzMxyGigznvouket4rk9sMC5zVYorfMhJlYnb3dYx8HirlJd9HQNBtuvqjmAcY=
  - secure: Hb/NtcM2nda7kGaGKAo3mKlrNkxV9irEbGjXuaIVyNzQy3h3fbiK4ZBKnHicToN5YionidkHogzecZ4lcaM1PAk3ewiD7T7RtA/jVYZ2S1+HGSu5RFCUJ+CJkSFarq0Z83Fof+ZpKEq7/5vXdMNPqVSYP1KcI9PiZc/RAYcKcbGo9DPAqIU5pOY67m1zzZ9Y0Lkhl8aLTq/QLzsGu1hQsK2t8WVG83+UDdu9fuw5EmhG67ujnP/EQIqkgxn2rf/Kkzy3FVpziAHhh0tlexdqRi2jKRMLFNp0X0kRuy0GthN6xQOufCAhz1G1o044fgIhtTtZvjU3PQ7lH1ciPbBK9qpvxKRDPMdnOP+FFdg71Ilvo0VQ4+OFWTESELaMzVId9U4RFZ4ZjjUGtcgOBZKn/+7NLd3GpIDOEqvkWSVXLMM4zV8vIMLPLH8rSAV10NSmSrLWWa0TayqoKbWVQVMEZo8PK1iCYpW8WeIVYcVn5oCEGvWmJUmVLcn2c69LUfm/dWI6RJ8k0SR+FBiSbZN3VIq2KYdiKkQKE42BwPTXNAI2ce2/3vOYWk2CWkzDT3vwWJz2cXx8ACeBAbWJHbA+8n/tli4JCT9bRQIFkt41CUVCi5BZUyW+4jrMQsE+Q03Lzhve1KC2FSdO921GGjC6vpORNI8AItPgJqB2G2KD86E=
